/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista_administrativo;

import Dtos.ComputadoraDTO;
import Dtos.ConsultarEstudianteDTO;
import componentes.ButtonEditor;
import componentes.ButtonRenderer;
import excepciones.NegocioException;
import interfaces.IAdministrativoNegocio;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ang3lfco
 */
public class frmComputadoras extends javax.swing.JFrame {
    private IAdministrativoNegocio adminNegocio;
    /**
     * Creates new form frmComputadoras
     */
    public frmComputadoras(IAdministrativoNegocio adminNegocio) {
        initComponents();
        
        
        this.adminNegocio = adminNegocio;
        try {
            cargarDatos();
            configurarTabla();
        } catch (NegocioException ex) {
            Logger.getLogger(frmComputadoras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarDatos() throws NegocioException {
        List<ComputadoraDTO> ArrayList;
        
//        List<ComputadoraDTO> pcs = adminNegocio.getComputadoras();
        List<ComputadoraDTO> pcs = adminNegocio.getComputadoras();
        DefaultTableModel model = (DefaultTableModel) tblPcs.getModel();
        model.setRowCount(0);
        for(ComputadoraDTO c : pcs){
            Object[] row = new Object[5];
            row[0] = c.getNumero();
            row[1] = c.isEstado();
            row[2] = c.getDireccionIp();
            row[3] = c.getTipo();
            row[4] = c.getLaboratorio().getNombre();
            model.addRow(row);
        }
        tblPcs.setRowHeight(50);
    }
    
    private void configurarTabla() {
        tblPcs.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer());

        ButtonEditor editor = new ButtonEditor(
            e -> {
                int fila = tblPcs.getSelectedRow();
                if (fila >= 0){
                    
                }
                JOptionPane.showMessageDialog(tblPcs, "Seleccionaste una fila para editar.");
            },
            e -> {
                JOptionPane.showMessageDialog(tblPcs, "Seleccionaste una fila para eliminar.");
            }
        );

        tblPcs.getColumnModel().getColumn(5).setCellEditor(editor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPcs = new javax.swing.JTable();
        lblAgregarComputadora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 109, 183));

        tblPcs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Estado", "IP", "Tipo", "Laboratorio", ""
            }
        ));
        jScrollPane1.setViewportView(tblPcs);

        lblAgregarComputadora.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblAgregarComputadora.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarComputadora.setText("+ Agregar Computadora");
        lblAgregarComputadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarComputadoraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblAgregarComputadora)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblAgregarComputadora)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAgregarComputadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarComputadoraMouseClicked
        // TODO add your handling code here:
        frmEquipo agregarEquipo = new frmEquipo(adminNegocio);
        agregarEquipo.setVisible(true);
    }//GEN-LAST:event_lblAgregarComputadoraMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmComputadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmComputadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmComputadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmComputadoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmComputadoras().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregarComputadora;
    private javax.swing.JTable tblPcs;
    // End of variables declaration//GEN-END:variables
}
